#swarm -f Comb_unique.NH_all.sh --verbose 1 -g 50 -t 32 -b 1 --time 24:00:00 --job-name Comb_unique.NH_all.sh --module samtools,novocraft

samtools merge /data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt_all.unique.NH.bam /data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bo.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ch.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.do.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cl.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bc.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.am.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cq.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cm.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.af.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ap.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cx.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cf.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.aw.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.br.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cj.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ae.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ed.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.db.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ct.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.au.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bp.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.at.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.an.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dn.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.be.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cb.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ao.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ah.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cw.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bv.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.aq.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.co.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ac.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ei.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.as.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dc.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bf.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dp.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cv.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bh.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.az.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.av.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ea.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bd.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ef.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ej.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ai.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ar.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.al.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ds.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ci.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ba.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bj.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cc.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dk.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ec.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.da.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ak.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ca.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bq.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cs.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bz.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dl.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dq.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.aj.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ax.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ck.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bb.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bi.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cd.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cp.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ab.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.df.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dy.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bu.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bs.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.eh.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bt.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bx.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cn.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ay.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bn.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cz.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.de.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cy.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bm.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.aa.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dt.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dz.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.eb.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bw.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ee.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ad.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.du.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cr.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.by.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.di.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ag.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dm.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cu.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dx.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bk.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bg.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dh.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.ce.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dv.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dr.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.eg.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.cg.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dj.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.bl.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dd.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dg.all.unique.NH.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/unique/Ro_Clip_iCountcutadpt.split.dw.all.unique.NH.bam 
