#swarm -f Comb_mm_all.sh --verbose 1 -g 50 -t 32 -b 1 --time 24:00:00 --job-name Comb_mm_all.sh --module samtools,novocraft

samtools merge /data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt_all.mm.bam /data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ac.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bl.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bc.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dp.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.br.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cr.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dj.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bo.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.az.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dd.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.aj.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.du.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cu.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bj.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ax.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bt.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bn.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ap.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cy.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ea.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cv.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dx.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dr.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.df.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.aq.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bi.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cg.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.am.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.aw.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.by.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.be.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bw.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bh.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bu.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ef.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bq.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.aa.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dq.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.do.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.al.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cj.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cf.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ec.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dw.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bs.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bm.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cl.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ag.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.af.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ay.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ad.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cd.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.de.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cp.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cn.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.eh.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ch.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.eg.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bb.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cq.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ba.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.db.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dh.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ar.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dv.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ao.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.di.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ci.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.at.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cm.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dy.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.da.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.eb.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ai.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cw.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ed.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ak.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cx.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ee.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bx.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dc.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bk.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bf.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bp.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ab.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.co.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.an.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dk.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ct.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cb.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dl.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ei.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dm.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bg.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bz.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ah.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bd.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cc.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ds.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cs.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.as.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dg.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ae.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ca.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.au.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ck.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dz.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dn.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ce.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.av.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.dt.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.bv.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.cz.all.mm.bam \
/data/RBL_NCI/Wolin/Phil/mESC_clip/Novo_UMI_split/bam_icountprocess/mm10_Gencode_rRNA/iCount_all/sep_MM_Uniq/multimap/bam_mm/Ro_Clip_iCountcutadpt.split.ej.all.mm.bam 
